// ═══════════════════════════════════════════════════════════════
// BETA COLLECTION TRACKER
// ═══════════════════════════════════════════════════════════════
// To update: uncomment card names in the `have` array below
// as you acquire them. Rebuild the site and the page updates.
//
// Basic lands have 3 art variants each (15 total), tracked
// individually as e.g. "Forest (A)", "Forest (B)", "Forest (C)".
// ═══════════════════════════════════════════════════════════════

// Last time you updated this list.
const lastUpdated = "2026-03-20";

// ───────────────────────────────────────────────────────────────
// Cards you own — uncomment lines as you acquire them
// ───────────────────────────────────────────────────────────────
const have = [
  // ── White ──────────────────────────────────────────────────
  // "Animate Wall",
  // "Armageddon",
  // "Balance",
  // "Benalish Hero",
  // "Black Ward",
  // "Blaze of Glory",
  // "Blessing",
  // "Blue Ward",
  // "Castle",
  // "Circle of Protection: Black",
  // "Circle of Protection: Blue",
  // "Circle of Protection: Green",
  // "Circle of Protection: Red",
  // "Circle of Protection: White",
  // "Consecrate Land",
  // "Conversion",
  // "Crusade",
  // "Death Ward",
  // "Disenchant",
  // "Farmstead",
  // "Green Ward",
  // "Guardian Angel",
  // "Healing Salve",
  // "Holy Armor",
  // "Holy Strength",
  // "Island Sanctuary",
  // "Karma",
  // "Lance",
  // "Mesa Pegasus",
  // "Northern Paladin",
  // "Pearled Unicorn",
  // "Personal Incarnation",
  // "Purelace",
  // "Red Ward",
  // "Resurrection",
  // "Reverse Damage",
  // "Righteousness",
  // "Samite Healer",
  // "Savannah Lions",
  // "Serra Angel",
  // "Swords to Plowshares",
  // "Veteran Bodyguard",
  // "Wall of Swords",
  // "White Knight",
  // "White Ward",
  // "Wrath of God",

  // ── Blue ───────────────────────────────────────────────────
  // "Air Elemental",
  // "Ancestral Recall",
  // "Animate Artifact",
  // "Blue Elemental Blast",
  // "Braingeyser",
  // "Clone",
  // "Control Magic",
  // "Copy Artifact",
  // "Counterspell",
  // "Creature Bond",
  // "Drain Power",
  // "Feedback",
  // "Flight",
  // "Invisibility",
  // "Jump",
  // "Lifetap",
  // "Lord of Atlantis",
  // "Magical Hack",
  // "Mahamoti Djinn",
  // "Mana Short",
  // "Merfolk of the Pearl Trident",
  // "Phantasmal Forces",
  // "Phantasmal Terrain",
  // "Phantom Monster",
  // "Pirate Ship",
  // "Power Leak",
  // "Power Sink",
  // "Prodigal Sorcerer",
  // "Psionic Blast",
  // "Psychic Venom",
  // "Sea Serpent",
  // "Siren's Call",
  // "Sleight of Mind",
  // "Spell Blast",
  // "Stasis",
  // "Steal Artifact",
  // "Thoughtlace",
  // "Time Walk",
  // "Timetwister",
  // "Twiddle",
  // "Unsummon",
  // "Vesuvan Doppelganger",
  // "Volcanic Eruption",
  // "Wall of Air",
  // "Wall of Water",
  // "Water Elemental",

  // ── Black ──────────────────────────────────────────────────
  // "Animate Dead",
  // "Bad Moon",
  // "Black Knight",
  // "Bog Wraith",
  // "Contract from Below",
  // "Cursed Land",
  // "Dark Ritual",
  // "Darkpact",
  // "Deathgrip",
  // "Deathlace",
  // "Demonic Attorney",
  // "Demonic Hordes",
  // "Demonic Tutor",
  // "Drain Life",
  // "Drudge Skeletons",
  // "Evil Presence",
  // "Fear",
  // "Frozen Shade",
  // "Gloom",
  // "Howl from Beyond",
  // "Hypnotic Specter",
  // "Lich",
  // "Lord of the Pit",
  // "Mind Twist",
  // "Nether Shadow",
  // "Nettling Imp",
  // "Nightmare",
  // "Paralyze",
  // "Pestilence",
  // "Plague Rats",
  // "Raise Dead",
  // "Royal Assassin",
  // "Sacrifice",
  // "Scathe Zombies",
  // "Scavenging Ghoul",
  // "Sengir Vampire",
  // "Simulacrum",
  // "Sinkhole",
  // "Terror",
  // "Unholy Strength",
  // "Wall of Bone",
  // "Warp Artifact",
  // "Weakness",
  // "Will-o'-the-Wisp",
  // "Word of Command",
  // "Zombie Master",

  // ── Red ────────────────────────────────────────────────────
  // "Burrowing",
  // "Chaoslace",
  // "Disintegrate",
  // "Dragon Whelp",
  // "Dwarven Demolition Team",
  // "Dwarven Warriors",
  // "Earth Elemental",
  // "Earthbind",
  // "Earthquake",
  // "False Orders",
  // "Fire Elemental",
  // "Fireball",
  // "Firebreathing",
  // "Flashfires",
  // "Fork",
  // "Goblin Balloon Brigade",
  // "Goblin King",
  // "Granite Gargoyle",
  // "Gray Ogre",
  // "Hill Giant",
  // "Hurloon Minotaur",
  // "Ironclaw Orcs",
  // "Keldon Warlord",
  // "Lightning Bolt",
  // "Mana Flare",
  // "Manabarbs",
  // "Mons's Goblin Raiders",
  // "Orcish Artillery",
  // "Orcish Oriflamme",
  // "Power Surge",
  // "Raging River",
  // "Red Elemental Blast",
  // "Rock Hydra",
  // "Roc of Kher Ridges",
  // "Sedge Troll",
  // "Shatter",
  // "Shivan Dragon",
  // "Smoke",
  // "Stone Giant",
  // "Stone Rain",
  // "Tunnel",
  // "Two-Headed Giant of Foriys",
  // "Uthden Troll",
  // "Wall of Fire",
  // "Wall of Stone",
  // "Wheel of Fortune",

  // ── Green ──────────────────────────────────────────────────
  // "Aspect of Wolf",
  // "Berserk",
  // "Birds of Paradise",
  // "Camouflage",
  // "Channel",
  // "Cockatrice",
  // "Craw Wurm",
  // "Elvish Archers",
  // "Fastbond",
  // "Fog",
  // "Force of Nature",
  // "Fungusaur",
  // "Gaea's Liege",
  // "Giant Growth",
  // "Giant Spider",
  // "Grizzly Bears",
  // "Hurricane",
  // "Ice Storm",
  // "Instill Energy",
  // "Ironroot Treefolk",
  // "Kudzu",
  // "Ley Druid",
  // "Lifeforce",
  // "Lifelace",
  // "Living Artifact",
  // "Living Lands",
  // "Llanowar Elves",
  // "Lure",
  // "Natural Selection",
  // "Regeneration",
  // "Regrowth",
  // "Scryb Sprites",
  // "Shanodin Dryads",
  // "Stream of Life",
  // "Thicket Basilisk",
  // "Timber Wolves",
  // "Tranquility",
  // "Tsunami",
  // "Verduran Enchantress",
  // "Wall of Brambles",
  // "Wall of Ice",
  // "Wall of Wood",
  // "Wanderlust",
  // "War Mammoth",
  // "Web",
  // "Wild Growth",

  // ── Artifacts ──────────────────────────────────────────────
  // "Ankh of Mishra",
  // "Basalt Monolith",
  // "Black Lotus",
  // "Black Vise",
  // "Celestial Prism",
  // "Chaos Orb",
  // "Clockwork Beast",
  // "Conservator",
  // "Copper Tablet",
  // "Crystal Rod",
  // "Cyclopean Tomb",
  // "Dingus Egg",
  // "Disrupting Scepter",
  // "Forcefield",
  // "Gauntlet of Might",
  // "Glasses of Urza",
  // "Helm of Chatzuk",
  // "Howling Mine",
  // "Icy Manipulator",
  // "Illusionary Mask",
  // "Iron Star",
  // "Ivory Cup",
  // "Jade Monolith",
  // "Jade Statue",
  // "Jayemdae Tome",
  // "Juggernaut",
  // "Kormus Bell",
  // "Library of Leng",
  // "Living Wall",
  // "Mana Vault",
  // "Meekstone",
  // "Mox Emerald",
  // "Mox Jet",
  // "Mox Pearl",
  // "Mox Ruby",
  // "Mox Sapphire",
  // "Nevinyrral's Disk",
  // "Obsianus Golem",
  // "Rod of Ruin",
  // "Sol Ring",
  // "Soul Net",
  // "Sunglasses of Urza",
  // "The Hive",
  // "Throne of Bone",
  // "Time Vault",
  // "Winter Orb",
  // "Wooden Sphere",

  // ── Lands ──────────────────────────────────────────────────
  // "Badlands",
  // "Bayou",
  // "Forest (A)",
  // "Forest (B)",
  // "Forest (C)",
  // "Island (A)",
  // "Island (B)",
  // "Island (C)",
  // "Mountain (A)",
  // "Mountain (B)",
  // "Mountain (C)",
  // "Plains (A)",
  // "Plains (B)",
  // "Plains (C)",
  // "Plateau",
  // "Savannah",
  // "Scrubland",
  // "Swamp (A)",
  // "Swamp (B)",
  // "Swamp (C)",
  // "Taiga",
  // "Tropical Island",
  // "Tundra",
  // "Underground Sea",
  // "Volcanic Island",
];

// ───────────────────────────────────────────────────────────────
// Cards you have extras of, available for trading
// ───────────────────────────────────────────────────────────────
const forTrade = [
  // "Lightning Bolt",
];

// ───────────────────────────────────────────────────────────────
// Per-card notes (condition, provenance, etc.)
// ───────────────────────────────────────────────────────────────
const cardNotes = {
  // "Lightning Bolt": "MP, light play on edges",
};

// ═══════════════════════════════════════════════════════════════
// CARD DATABASE — sourced from Scryfall (set:leb)
// Edit only to correct data or add basic land art variants.
// ═══════════════════════════════════════════════════════════════

const cards = [
  // White
  { name: "Animate Wall", color: "White", rarity: "R", type: "Enchantment" },
  { name: "Armageddon", color: "White", rarity: "R", type: "Sorcery" },
  { name: "Balance", color: "White", rarity: "R", type: "Sorcery" },
  { name: "Benalish Hero", color: "White", rarity: "C", type: "Creature" },
  { name: "Black Ward", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Blaze of Glory", color: "White", rarity: "R", type: "Instant" },
  { name: "Blessing", color: "White", rarity: "R", type: "Enchantment" },
  { name: "Blue Ward", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Castle", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Circle of Protection: Black", color: "White", rarity: "C", type: "Enchantment" },
  { name: "Circle of Protection: Blue", color: "White", rarity: "C", type: "Enchantment" },
  { name: "Circle of Protection: Green", color: "White", rarity: "C", type: "Enchantment" },
  { name: "Circle of Protection: Red", color: "White", rarity: "C", type: "Enchantment" },
  { name: "Circle of Protection: White", color: "White", rarity: "C", type: "Enchantment" },
  { name: "Consecrate Land", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Conversion", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Crusade", color: "White", rarity: "R", type: "Enchantment" },
  { name: "Death Ward", color: "White", rarity: "C", type: "Instant" },
  { name: "Disenchant", color: "White", rarity: "C", type: "Instant" },
  { name: "Farmstead", color: "White", rarity: "R", type: "Enchantment" },
  { name: "Green Ward", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Guardian Angel", color: "White", rarity: "C", type: "Instant" },
  { name: "Healing Salve", color: "White", rarity: "C", type: "Instant" },
  { name: "Holy Armor", color: "White", rarity: "C", type: "Enchantment" },
  { name: "Holy Strength", color: "White", rarity: "C", type: "Enchantment" },
  { name: "Island Sanctuary", color: "White", rarity: "R", type: "Enchantment" },
  { name: "Karma", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Lance", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Mesa Pegasus", color: "White", rarity: "C", type: "Creature" },
  { name: "Northern Paladin", color: "White", rarity: "R", type: "Creature" },
  { name: "Pearled Unicorn", color: "White", rarity: "C", type: "Creature" },
  { name: "Personal Incarnation", color: "White", rarity: "R", type: "Creature" },
  { name: "Purelace", color: "White", rarity: "R", type: "Instant" },
  { name: "Red Ward", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Resurrection", color: "White", rarity: "U", type: "Sorcery" },
  { name: "Reverse Damage", color: "White", rarity: "R", type: "Instant" },
  { name: "Righteousness", color: "White", rarity: "R", type: "Instant" },
  { name: "Samite Healer", color: "White", rarity: "C", type: "Creature" },
  { name: "Savannah Lions", color: "White", rarity: "R", type: "Creature" },
  { name: "Serra Angel", color: "White", rarity: "U", type: "Creature" },
  { name: "Swords to Plowshares", color: "White", rarity: "U", type: "Instant" },
  { name: "Veteran Bodyguard", color: "White", rarity: "R", type: "Creature" },
  { name: "Wall of Swords", color: "White", rarity: "U", type: "Creature" },
  { name: "White Knight", color: "White", rarity: "U", type: "Creature" },
  { name: "White Ward", color: "White", rarity: "U", type: "Enchantment" },
  { name: "Wrath of God", color: "White", rarity: "R", type: "Sorcery" },
  // Blue
  { name: "Air Elemental", color: "Blue", rarity: "U", type: "Creature" },
  { name: "Ancestral Recall", color: "Blue", rarity: "R", type: "Instant" },
  { name: "Animate Artifact", color: "Blue", rarity: "U", type: "Enchantment" },
  { name: "Blue Elemental Blast", color: "Blue", rarity: "C", type: "Instant" },
  { name: "Braingeyser", color: "Blue", rarity: "R", type: "Sorcery" },
  { name: "Clone", color: "Blue", rarity: "U", type: "Creature" },
  { name: "Control Magic", color: "Blue", rarity: "U", type: "Enchantment" },
  { name: "Copy Artifact", color: "Blue", rarity: "R", type: "Enchantment" },
  { name: "Counterspell", color: "Blue", rarity: "U", type: "Instant" },
  { name: "Creature Bond", color: "Blue", rarity: "C", type: "Enchantment" },
  { name: "Drain Power", color: "Blue", rarity: "R", type: "Sorcery" },
  { name: "Feedback", color: "Blue", rarity: "U", type: "Enchantment" },
  { name: "Flight", color: "Blue", rarity: "C", type: "Enchantment" },
  { name: "Invisibility", color: "Blue", rarity: "C", type: "Enchantment" },
  { name: "Jump", color: "Blue", rarity: "C", type: "Instant" },
  { name: "Lifetap", color: "Blue", rarity: "U", type: "Enchantment" },
  { name: "Lord of Atlantis", color: "Blue", rarity: "R", type: "Creature" },
  { name: "Magical Hack", color: "Blue", rarity: "R", type: "Instant" },
  { name: "Mahamoti Djinn", color: "Blue", rarity: "R", type: "Creature" },
  { name: "Mana Short", color: "Blue", rarity: "R", type: "Instant" },
  { name: "Merfolk of the Pearl Trident", color: "Blue", rarity: "C", type: "Creature" },
  { name: "Phantasmal Forces", color: "Blue", rarity: "U", type: "Creature" },
  { name: "Phantasmal Terrain", color: "Blue", rarity: "C", type: "Enchantment" },
  { name: "Phantom Monster", color: "Blue", rarity: "U", type: "Creature" },
  { name: "Pirate Ship", color: "Blue", rarity: "R", type: "Creature" },
  { name: "Power Leak", color: "Blue", rarity: "C", type: "Enchantment" },
  { name: "Power Sink", color: "Blue", rarity: "C", type: "Instant" },
  { name: "Prodigal Sorcerer", color: "Blue", rarity: "C", type: "Creature" },
  { name: "Psionic Blast", color: "Blue", rarity: "U", type: "Instant" },
  { name: "Psychic Venom", color: "Blue", rarity: "C", type: "Enchantment" },
  { name: "Sea Serpent", color: "Blue", rarity: "C", type: "Creature" },
  { name: "Siren's Call", color: "Blue", rarity: "U", type: "Instant" },
  { name: "Sleight of Mind", color: "Blue", rarity: "R", type: "Instant" },
  { name: "Spell Blast", color: "Blue", rarity: "C", type: "Instant" },
  { name: "Stasis", color: "Blue", rarity: "R", type: "Enchantment" },
  { name: "Steal Artifact", color: "Blue", rarity: "U", type: "Enchantment" },
  { name: "Thoughtlace", color: "Blue", rarity: "R", type: "Instant" },
  { name: "Time Walk", color: "Blue", rarity: "R", type: "Sorcery" },
  { name: "Timetwister", color: "Blue", rarity: "R", type: "Sorcery" },
  { name: "Twiddle", color: "Blue", rarity: "C", type: "Instant" },
  { name: "Unsummon", color: "Blue", rarity: "C", type: "Instant" },
  { name: "Vesuvan Doppelganger", color: "Blue", rarity: "R", type: "Creature" },
  { name: "Volcanic Eruption", color: "Blue", rarity: "R", type: "Sorcery" },
  { name: "Wall of Air", color: "Blue", rarity: "U", type: "Creature" },
  { name: "Wall of Water", color: "Blue", rarity: "U", type: "Creature" },
  { name: "Water Elemental", color: "Blue", rarity: "U", type: "Creature" },
  // Black
  { name: "Animate Dead", color: "Black", rarity: "U", type: "Enchantment" },
  { name: "Bad Moon", color: "Black", rarity: "R", type: "Enchantment" },
  { name: "Black Knight", color: "Black", rarity: "U", type: "Creature" },
  { name: "Bog Wraith", color: "Black", rarity: "U", type: "Creature" },
  { name: "Contract from Below", color: "Black", rarity: "R", type: "Sorcery" },
  { name: "Cursed Land", color: "Black", rarity: "U", type: "Enchantment" },
  { name: "Dark Ritual", color: "Black", rarity: "C", type: "Instant" },
  { name: "Darkpact", color: "Black", rarity: "R", type: "Sorcery" },
  { name: "Deathgrip", color: "Black", rarity: "U", type: "Enchantment" },
  { name: "Deathlace", color: "Black", rarity: "R", type: "Instant" },
  { name: "Demonic Attorney", color: "Black", rarity: "R", type: "Sorcery" },
  { name: "Demonic Hordes", color: "Black", rarity: "R", type: "Creature" },
  { name: "Demonic Tutor", color: "Black", rarity: "U", type: "Sorcery" },
  { name: "Drain Life", color: "Black", rarity: "C", type: "Sorcery" },
  { name: "Drudge Skeletons", color: "Black", rarity: "C", type: "Creature" },
  { name: "Evil Presence", color: "Black", rarity: "U", type: "Enchantment" },
  { name: "Fear", color: "Black", rarity: "C", type: "Enchantment" },
  { name: "Frozen Shade", color: "Black", rarity: "C", type: "Creature" },
  { name: "Gloom", color: "Black", rarity: "U", type: "Enchantment" },
  { name: "Howl from Beyond", color: "Black", rarity: "C", type: "Instant" },
  { name: "Hypnotic Specter", color: "Black", rarity: "U", type: "Creature" },
  { name: "Lich", color: "Black", rarity: "R", type: "Enchantment" },
  { name: "Lord of the Pit", color: "Black", rarity: "R", type: "Creature" },
  { name: "Mind Twist", color: "Black", rarity: "R", type: "Sorcery" },
  { name: "Nether Shadow", color: "Black", rarity: "R", type: "Creature" },
  { name: "Nettling Imp", color: "Black", rarity: "U", type: "Creature" },
  { name: "Nightmare", color: "Black", rarity: "R", type: "Creature" },
  { name: "Paralyze", color: "Black", rarity: "C", type: "Enchantment" },
  { name: "Pestilence", color: "Black", rarity: "C", type: "Enchantment" },
  { name: "Plague Rats", color: "Black", rarity: "C", type: "Creature" },
  { name: "Raise Dead", color: "Black", rarity: "C", type: "Sorcery" },
  { name: "Royal Assassin", color: "Black", rarity: "R", type: "Creature" },
  { name: "Sacrifice", color: "Black", rarity: "U", type: "Instant" },
  { name: "Scathe Zombies", color: "Black", rarity: "C", type: "Creature" },
  { name: "Scavenging Ghoul", color: "Black", rarity: "U", type: "Creature" },
  { name: "Sengir Vampire", color: "Black", rarity: "U", type: "Creature" },
  { name: "Simulacrum", color: "Black", rarity: "U", type: "Instant" },
  { name: "Sinkhole", color: "Black", rarity: "C", type: "Sorcery" },
  { name: "Terror", color: "Black", rarity: "C", type: "Instant" },
  { name: "Unholy Strength", color: "Black", rarity: "C", type: "Enchantment" },
  { name: "Wall of Bone", color: "Black", rarity: "U", type: "Creature" },
  { name: "Warp Artifact", color: "Black", rarity: "R", type: "Enchantment" },
  { name: "Weakness", color: "Black", rarity: "C", type: "Enchantment" },
  { name: "Will-o'-the-Wisp", color: "Black", rarity: "R", type: "Creature" },
  { name: "Word of Command", color: "Black", rarity: "R", type: "Instant" },
  { name: "Zombie Master", color: "Black", rarity: "R", type: "Creature" },
  // Red
  { name: "Burrowing", color: "Red", rarity: "U", type: "Enchantment" },
  { name: "Chaoslace", color: "Red", rarity: "R", type: "Instant" },
  { name: "Disintegrate", color: "Red", rarity: "C", type: "Sorcery" },
  { name: "Dragon Whelp", color: "Red", rarity: "U", type: "Creature" },
  { name: "Dwarven Demolition Team", color: "Red", rarity: "U", type: "Creature" },
  { name: "Dwarven Warriors", color: "Red", rarity: "C", type: "Creature" },
  { name: "Earth Elemental", color: "Red", rarity: "U", type: "Creature" },
  { name: "Earthbind", color: "Red", rarity: "C", type: "Enchantment" },
  { name: "Earthquake", color: "Red", rarity: "R", type: "Sorcery" },
  { name: "False Orders", color: "Red", rarity: "C", type: "Instant" },
  { name: "Fire Elemental", color: "Red", rarity: "U", type: "Creature" },
  { name: "Fireball", color: "Red", rarity: "C", type: "Sorcery" },
  { name: "Firebreathing", color: "Red", rarity: "C", type: "Enchantment" },
  { name: "Flashfires", color: "Red", rarity: "U", type: "Sorcery" },
  { name: "Fork", color: "Red", rarity: "R", type: "Instant" },
  { name: "Goblin Balloon Brigade", color: "Red", rarity: "U", type: "Creature" },
  { name: "Goblin King", color: "Red", rarity: "R", type: "Creature" },
  { name: "Granite Gargoyle", color: "Red", rarity: "R", type: "Creature" },
  { name: "Gray Ogre", color: "Red", rarity: "C", type: "Creature" },
  { name: "Hill Giant", color: "Red", rarity: "C", type: "Creature" },
  { name: "Hurloon Minotaur", color: "Red", rarity: "C", type: "Creature" },
  { name: "Ironclaw Orcs", color: "Red", rarity: "C", type: "Creature" },
  { name: "Keldon Warlord", color: "Red", rarity: "U", type: "Creature" },
  { name: "Lightning Bolt", color: "Red", rarity: "C", type: "Instant" },
  { name: "Mana Flare", color: "Red", rarity: "R", type: "Enchantment" },
  { name: "Manabarbs", color: "Red", rarity: "R", type: "Enchantment" },
  { name: "Mons's Goblin Raiders", color: "Red", rarity: "C", type: "Creature" },
  { name: "Orcish Artillery", color: "Red", rarity: "U", type: "Creature" },
  { name: "Orcish Oriflamme", color: "Red", rarity: "U", type: "Enchantment" },
  { name: "Power Surge", color: "Red", rarity: "R", type: "Enchantment" },
  { name: "Raging River", color: "Red", rarity: "R", type: "Enchantment" },
  { name: "Red Elemental Blast", color: "Red", rarity: "C", type: "Instant" },
  { name: "Rock Hydra", color: "Red", rarity: "R", type: "Creature" },
  { name: "Roc of Kher Ridges", color: "Red", rarity: "R", type: "Creature" },
  { name: "Sedge Troll", color: "Red", rarity: "R", type: "Creature" },
  { name: "Shatter", color: "Red", rarity: "C", type: "Instant" },
  { name: "Shivan Dragon", color: "Red", rarity: "R", type: "Creature" },
  { name: "Smoke", color: "Red", rarity: "R", type: "Enchantment" },
  { name: "Stone Giant", color: "Red", rarity: "U", type: "Creature" },
  { name: "Stone Rain", color: "Red", rarity: "C", type: "Sorcery" },
  { name: "Tunnel", color: "Red", rarity: "U", type: "Instant" },
  { name: "Two-Headed Giant of Foriys", color: "Red", rarity: "R", type: "Creature" },
  { name: "Uthden Troll", color: "Red", rarity: "U", type: "Creature" },
  { name: "Wall of Fire", color: "Red", rarity: "U", type: "Creature" },
  { name: "Wall of Stone", color: "Red", rarity: "U", type: "Creature" },
  { name: "Wheel of Fortune", color: "Red", rarity: "R", type: "Sorcery" },
  // Green
  { name: "Aspect of Wolf", color: "Green", rarity: "R", type: "Enchantment" },
  { name: "Berserk", color: "Green", rarity: "U", type: "Instant" },
  { name: "Birds of Paradise", color: "Green", rarity: "R", type: "Creature" },
  { name: "Camouflage", color: "Green", rarity: "U", type: "Instant" },
  { name: "Channel", color: "Green", rarity: "U", type: "Sorcery" },
  { name: "Cockatrice", color: "Green", rarity: "R", type: "Creature" },
  { name: "Craw Wurm", color: "Green", rarity: "C", type: "Creature" },
  { name: "Elvish Archers", color: "Green", rarity: "R", type: "Creature" },
  { name: "Fastbond", color: "Green", rarity: "R", type: "Enchantment" },
  { name: "Fog", color: "Green", rarity: "C", type: "Instant" },
  { name: "Force of Nature", color: "Green", rarity: "R", type: "Creature" },
  { name: "Fungusaur", color: "Green", rarity: "R", type: "Creature" },
  { name: "Gaea's Liege", color: "Green", rarity: "R", type: "Creature" },
  { name: "Giant Growth", color: "Green", rarity: "C", type: "Instant" },
  { name: "Giant Spider", color: "Green", rarity: "C", type: "Creature" },
  { name: "Grizzly Bears", color: "Green", rarity: "C", type: "Creature" },
  { name: "Hurricane", color: "Green", rarity: "U", type: "Sorcery" },
  { name: "Ice Storm", color: "Green", rarity: "U", type: "Sorcery" },
  { name: "Instill Energy", color: "Green", rarity: "U", type: "Enchantment" },
  { name: "Ironroot Treefolk", color: "Green", rarity: "C", type: "Creature" },
  { name: "Kudzu", color: "Green", rarity: "R", type: "Enchantment" },
  { name: "Ley Druid", color: "Green", rarity: "U", type: "Creature" },
  { name: "Lifeforce", color: "Green", rarity: "U", type: "Enchantment" },
  { name: "Lifelace", color: "Green", rarity: "R", type: "Instant" },
  { name: "Living Artifact", color: "Green", rarity: "R", type: "Enchantment" },
  { name: "Living Lands", color: "Green", rarity: "R", type: "Enchantment" },
  { name: "Llanowar Elves", color: "Green", rarity: "C", type: "Creature" },
  { name: "Lure", color: "Green", rarity: "U", type: "Enchantment" },
  { name: "Natural Selection", color: "Green", rarity: "R", type: "Instant" },
  { name: "Regeneration", color: "Green", rarity: "C", type: "Enchantment" },
  { name: "Regrowth", color: "Green", rarity: "U", type: "Sorcery" },
  { name: "Scryb Sprites", color: "Green", rarity: "C", type: "Creature" },
  { name: "Shanodin Dryads", color: "Green", rarity: "C", type: "Creature" },
  { name: "Stream of Life", color: "Green", rarity: "C", type: "Sorcery" },
  { name: "Thicket Basilisk", color: "Green", rarity: "U", type: "Creature" },
  { name: "Timber Wolves", color: "Green", rarity: "R", type: "Creature" },
  { name: "Tranquility", color: "Green", rarity: "C", type: "Sorcery" },
  { name: "Tsunami", color: "Green", rarity: "U", type: "Sorcery" },
  { name: "Verduran Enchantress", color: "Green", rarity: "R", type: "Creature" },
  { name: "Wall of Brambles", color: "Green", rarity: "U", type: "Creature" },
  { name: "Wall of Ice", color: "Green", rarity: "U", type: "Creature" },
  { name: "Wall of Wood", color: "Green", rarity: "C", type: "Creature" },
  { name: "Wanderlust", color: "Green", rarity: "U", type: "Enchantment" },
  { name: "War Mammoth", color: "Green", rarity: "C", type: "Creature" },
  { name: "Web", color: "Green", rarity: "R", type: "Enchantment" },
  { name: "Wild Growth", color: "Green", rarity: "C", type: "Enchantment" },
  // Artifacts
  { name: "Ankh of Mishra", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Basalt Monolith", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Black Lotus", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Black Vise", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Celestial Prism", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Chaos Orb", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Clockwork Beast", color: "Colorless", rarity: "R", type: "Artifact Creature" },
  { name: "Conservator", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Copper Tablet", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Crystal Rod", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Cyclopean Tomb", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Dingus Egg", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Disrupting Scepter", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Forcefield", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Gauntlet of Might", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Glasses of Urza", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Helm of Chatzuk", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Howling Mine", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Icy Manipulator", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Illusionary Mask", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Iron Star", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Ivory Cup", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Jade Monolith", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Jade Statue", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Jayemdae Tome", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Juggernaut", color: "Colorless", rarity: "U", type: "Artifact Creature" },
  { name: "Kormus Bell", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Library of Leng", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Living Wall", color: "Colorless", rarity: "U", type: "Artifact Creature" },
  { name: "Mana Vault", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Meekstone", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Mox Emerald", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Mox Jet", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Mox Pearl", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Mox Ruby", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Mox Sapphire", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Nevinyrral's Disk", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Obsianus Golem", color: "Colorless", rarity: "U", type: "Artifact Creature" },
  { name: "Rod of Ruin", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Sol Ring", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Soul Net", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Sunglasses of Urza", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "The Hive", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Throne of Bone", color: "Colorless", rarity: "U", type: "Artifact" },
  { name: "Time Vault", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Winter Orb", color: "Colorless", rarity: "R", type: "Artifact" },
  { name: "Wooden Sphere", color: "Colorless", rarity: "U", type: "Artifact" },
  // Lands
  { name: "Badlands", color: "Land", rarity: "R", type: "Land" },
  { name: "Bayou", color: "Land", rarity: "R", type: "Land" },
  { name: "Forest (A)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Forest (B)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Forest (C)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Island (A)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Island (B)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Island (C)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Mountain (A)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Mountain (B)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Mountain (C)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Plains (A)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Plains (B)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Plains (C)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Plateau", color: "Land", rarity: "R", type: "Land" },
  { name: "Savannah", color: "Land", rarity: "R", type: "Land" },
  { name: "Scrubland", color: "Land", rarity: "R", type: "Land" },
  { name: "Swamp (A)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Swamp (B)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Swamp (C)", color: "Land", rarity: "C", type: "Basic Land" },
  { name: "Taiga", color: "Land", rarity: "R", type: "Land" },
  { name: "Tropical Island", color: "Land", rarity: "R", type: "Land" },
  { name: "Tundra", color: "Land", rarity: "R", type: "Land" },
  { name: "Underground Sea", color: "Land", rarity: "R", type: "Land" },
  { name: "Volcanic Island", color: "Land", rarity: "R", type: "Land" },
];

// ═══════════════════════════════════════════════════════════════
// PROCESSING — generates template data from the above
// ═══════════════════════════════════════════════════════════════

const haveSet = new Set(have);
const tradeSet = new Set(forTrade);
const cardNameSet = new Set(cards.map(c => c.name));

// Flag any typos in the have/forTrade lists
const unrecognized = have
  .filter(name => !cardNameSet.has(name))
  .concat(forTrade.filter(name => !cardNameSet.has(name)));

const enriched = cards.map(c => ({
  ...c,
  have: haveSet.has(c.name),
  trade: tradeSet.has(c.name),
  note: cardNotes[c.name] || null,
}));

const colorOrder = ["White", "Blue", "Black", "Red", "Green", "Colorless", "Land"];
const colorLabels = {
  White: "White", Blue: "Blue", Black: "Black",
  Red: "Red", Green: "Green", Colorless: "Artifacts", Land: "Lands",
};

const byColor = {};
const colorStats = {};
for (const color of colorOrder) {
  const colorCards = enriched.filter(c => c.color === color)
    .sort((a, b) => a.name.localeCompare(b.name));
  byColor[color] = colorCards;
  const owned = colorCards.filter(c => c.have).length;
  colorStats[color] = {
    total: colorCards.length,
    owned,
    needed: colorCards.length - owned,
    percent: colorCards.length > 0 ? Math.round((owned / colorCards.length) * 100) : 0,
  };
}

const rarityLabels = { R: "Rare", U: "Uncommon", C: "Common" };
const neededByRarity = {};
for (const r of ["R", "U", "C"]) {
  neededByRarity[r] = enriched.filter(c => !c.have && c.rarity === r)
    .sort((a, b) => a.name.localeCompare(b.name));
}

const total = enriched.length;
const owned = enriched.filter(c => c.have).length;
const tradeable = enriched.filter(c => c.trade);

module.exports = {
  lastUpdated,
  cards: enriched,
  byColor,
  colorOrder,
  colorLabels,
  colorStats,
  neededByRarity,
  rarityLabels,
  total,
  owned,
  needed: total - owned,
  tradeable,
  percent: total > 0 ? Math.round((owned / total) * 100) : 0,
  unrecognized,
};
